// Build step for the shared payments client: `npm run build:pay`  (Cloudflare deploy has no build step, so the output is committed)
//  reads `treasury` from site/config.js (validated 32-byte base58) and bundles site-src/pay.js (+ @solana/kit,
//  @wallet-standard/app, tip-core) with esbuild → site/assets/pay.js (minified IIFE, treasury baked in; lazy-loaded by
//  /assets/pro.js). test/pay-core.test.js fails if the committed bundle is out of date.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { b58bytes } from '../src/tip.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const PAY_BUNDLE = 'site/assets/pay.js';

export function treasuryAddress(src = fs.readFileSync(path.join(ROOT, 'site', 'config.js'), 'utf8')) {
  const ctx = { window: {} }; vm.runInNewContext(src, ctx);
  const a = ctx.window.MAXIGEMS_CONFIG && ctx.window.MAXIGEMS_CONFIG.treasury;
  const b = typeof a === 'string' && /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(a) ? b58bytes(a) : null;
  return b && b.length === 32 ? a : null;
}

export async function buildPayBundle(addr = treasuryAddress()) {
  const esbuild = await import('esbuild');
  const r = await esbuild.build({
    entryPoints: [path.join(ROOT, 'site-src', 'pay.js')], absWorkingDir: ROOT, bundle: true, minify: true, format: 'iife',
    target: ['es2020'], platform: 'browser', write: false, legalComments: 'none', charset: 'utf8',
    define: { __TREASURY__: JSON.stringify(addr), 'process.env.NODE_ENV': '"production"' },
    banner: { js: '/* MaxiGems MGPay bundle — generated by `npm run build:pay`; do not edit. */' },
  });
  return Buffer.from(r.outputFiles[0].contents);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const addr = treasuryAddress();
  if (!addr) { console.error('treasury in site/config.js is missing or not a valid Solana address'); process.exit(1); }
  const b = await buildPayBundle(addr);
  fs.writeFileSync(path.join(ROOT, PAY_BUNDLE), b);
  // cache-bust: /assets/pro.js loads /assets/pay.js?v=<sha256[:10]>
  const v = (await import('node:crypto')).createHash('sha256').update(b).digest('hex').slice(0, 10);
  const pj = path.join(ROOT, 'site', 'assets', 'pro.js');
  fs.writeFileSync(pj, fs.readFileSync(pj, 'utf8').replace(/var PAY_SRC = '\/assets\/pay\.js\?v=[0-9a-f]*'/, `var PAY_SRC = '/assets/pay.js?v=${v}'`));
  console.log(`pay: treasury ${addr} → ${PAY_BUNDLE} (${(b.length / 1024).toFixed(1)} KB)`);
}
