// Build step for tipping: `npm run build:tip`  (GitHub Pages has no build step, so outputs are committed)
//  1. reads tipAddress from site/config.js (validated: 32-byte base58)
//  2. bundles site-src/tip-wallet.js (+ @solana/kit, @wallet-standard/app) with esbuild → site/assets/tip-wallet.js
//     (single minified IIFE, recipient baked in from config; lazy-loaded by /assets/tip.js when the modal opens)
//  3. injects the tip card between <!-- tip:start --> / <!-- tip:end --> markers in the static pages
//  4. re-renders existing coin pages (/c/<CA>/); the engine also regenerates them on every run.
// test/tip.test.js fails if the bundle or any page is out of date.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { tipAddress, tipCardHtml, resetBundleVersion, BUNDLE } from '../src/tip.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const STATIC_PAGES = ['index.html', 'trending/index.html', 'leaderboard/index.html', 'whales/index.html', '404.html'];

/** Deterministic bundle bytes (no file written). */
export async function buildBundle(addr = tipAddress()) {
  const esbuild = await import('esbuild');
  const r = await esbuild.build({
    entryPoints: [path.join(ROOT, 'site-src', 'tip-wallet.js')], absWorkingDir: ROOT, bundle: true, minify: true, format: 'iife',
    target: ['es2020'], platform: 'browser', write: false, legalComments: 'none', charset: 'utf8',
    define: { __TIP_RECIPIENT__: JSON.stringify(addr), 'process.env.NODE_ENV': '"production"' },
    banner: { js: '/* MaxiGems tip wallet bundle — generated by `npm run build:tip`; do not edit. */' },
  });
  return Buffer.from(r.outputFiles[0].contents);
}

export function inject(html, card) {
  const re = /<!-- tip:start -->[\s\S]*?<!-- tip:end -->/;
  if (!re.test(html)) throw new Error('missing tip markers');
  return html.replace(re, `<!-- tip:start -->\n  ${card}\n  <!-- tip:end -->`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const addr = tipAddress();
  if (!addr) { console.error('tipAddress in site/config.js is missing or not a valid Solana address'); process.exit(1); }
  const bundle = await buildBundle(addr);
  fs.writeFileSync(path.join(ROOT, BUNDLE), bundle);
  resetBundleVersion();
  const card = tipCardHtml(addr);
  for (const p of STATIC_PAGES) {
    const f = path.join(ROOT, 'site', p);
    fs.writeFileSync(f, inject(fs.readFileSync(f, 'utf8'), card));
  }
  // refresh existing coin pages too (same renderer as the engine), so they point at the new bundle version
  let coins = 0;
  try {
    const { coinPageHtml, templateParts } = await import('../src/share.js');
    const man = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'share.json'), 'utf8'));
    const calls = JSON.parse(fs.readFileSync(path.join(ROOT, 'site', 'data', 'calls.json'), 'utf8')).calls || [];
    const parts = templateParts();
    for (const c of calls) {
      const f = path.join(ROOT, 'site', 'c', String(c.address), 'index.html');
      if (!man.coins?.[c.address] || !fs.existsSync(f)) continue;
      fs.writeFileSync(f, coinPageHtml(c, man.coins[c.address], parts)); coins++;
    }
  } catch (e) { console.warn(`tip: coin pages not refreshed (${e.message})`); }
  console.log(`tip: ${addr} → ${BUNDLE} (${(bundle.length / 1024).toFixed(1)} KB) + ${STATIC_PAGES.length} pages + ${coins} coin pages`);
}
